### PR TITLE
add simplified chinese, update .gitignore

### PR DESCRIPTION
**Pull request by Icarus-Xu**
Hi zyrouge,

Plz kindly review this translation of simplified chinese.

Also, I would like to ask for the reason you choose to use generated individual .kt translation files instead of the strings.xml machanism android provided. AFAIK android supports (language)-r(Region) pattern, which is more accurate than symphony's current machanism, e.g. en-US / en-GB may vary in some words and zh-rCN / zh-rHK have a lot of different characters. In android 14 there will be a "set app language individually" setting built-in, and that feature would require no effort if we apply android machanism instead of current .kt one. So please enlighten me if you think current one is better.

Best
Icarus

### CODE REVIEW

**Comment by Icarus-Xu** [comment]
Oh and about this string:
"IsLocalPlaylist: Is local playlist?"

I don't think asking a question and answer it is the appropriate way to display some "details", so I did not translate it, would you think of another way to display that?

**Comment by zyrouge** [comment]
> Oh and about this string: "IsLocalPlaylist: Is local playlist?"
> 
> I don't think asking a question and answer it is the appropriate way to display some "details", so I did not translate it, would you think of another way to display that?

The only other possible way is to display whether it's "in-built" or "local" playlists, so possibly "Playlist Type" or just "Type" or "Kind".

**Comment by Icarus-Xu** [comment]
probably, that's better. so do you want me to take care of that modification or shall I wait for your patch and then refine my pr?

**Comment by zyrouge** [comment]
> probably, that's better. so do you want me to take care of that modification or shall I wait for your patch and then refine my pr?

If you could do it right, then go ahead. Lemme know if you could do that.

**Comment by Icarus-Xu** [comment]
I will take care of that asap.

and could you share your thought about the translation system thing i mentioned at first?

**Comment by Icarus-Xu** [comment]
playlist info has been taken care of, i also updated .gitignore to prevent local idea config being uploaded to github.

**Comment by zyrouge** [comment]
> playlist info has been taken care of, i also updated .gitignore to prevent local idea config being uploaded to github.

Ah, that does seem like a very good idea. I didn't implement country code to just make things easier, but would be adding it.

**Comment by Icarus-Xu** [comment]
I guest the "easiest" approach is to use built-in resource folders XD, anyway do whatever you like.

**Comment by zyrouge** [comment]
Also, support for country codes has been added!

**Pull request merged**
