### PR TITLE
Fixed some Japanese translations and added Uchinaguchi (うちなーぐち) translation

### PR DESCRIPTION
**Pull request by kuragehimekurara1**

### CODE REVIEW

**Comment by zyrouge** [comment]
LGTM!

**Comment by zyrouge** [comment]
Seems like Central Okinawan (`ryu`) is not a ISO locale code. What would be appropriate for this other than that locale code? I would not be able to include it if it's not supported.

**Comment by zyrouge** [comment]
My further research says it an "endangered language" and thus why it's not really considered in ISO-639. If you could help me out with detailed information about the language, I could add it myself even though it's not an ISO-639 language.

Display Name: `Central Okinawan`?
Native Name: `?`
Code: `ryu`

**Comment by kuragehimekurara1** [comment]
Okinawan (Uchinaguchi) is a Japanese language classified under ISO 639-3.  So I think you can add it like this:
display name:うちなーぐち
native name: Uchināguchi or Okinawan
code name: ryu

**Comment by kuragehimekurara1** [comment]
I looked up the native name myself, but I didn't really understand it, so I think Uchinaguchi or Okinawan would be fine, but I don't know.

**Comment by kuragehimekurara1** [comment]
I looked up the native name myself, but I didn't really understand it, so I think Uchinaguchi or Okinawan would be fine, but I don't know.

**Comment by zyrouge** [comment]
ISO 639-3 does document this but most of the specifications don't seem to include this. BCP47 does not consider it but Unicode CLDR has marked it as possibly a sub-tag. Well, specifications don't really matter here.

I'll go with `Okinawan` since `Uchinaguchi` is the pronunciation. Thank you for your contribution! :)

**Comment by kuragehimekurara1** [comment]
No Problem! :)

**Pull request merged**
