### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by userkilled**
In general, I tried to translate part for the test, I hope that the large, application

ru.yaml is almost all, but Russian.kt will need to translate and add untranslated lines

### CODE REVIEW

**Comment by zyrouge** [comment]
You do not have to create `Russian.kt`. Just complete the `ry.yaml` file.

**Comment by userkilled** [comment]
Good< thank you

**Comment by zyrouge** [comment]
Could you mark it as draft until it is finished?

**Comment by userkilled** [comment]
Now I translated what I could understand and was just to see inside the application

**Comment by zyrouge** [comment]
Could you update with update, more sentences were added.

**Comment by userkilled** [comment]
Yes, of course

**Comment by zyrouge** [comment]
Mark this as open when it's ready.

**Comment by zyrouge** [comment]
Seems like Russian was added in #108. Appreciate the attempt to contribute!

**Pull request closed without merging**
