### PR TITLE
Fix #111 - Customizable speed and pitch

### LINKED ISSUE #111: [Feature Request] Customizable speed and pitch
As the title says, it would be great if you add an option to have customizable speed and pitch, such as adding a slider or type the custom value (e.g. 1.05 or 1.1). It would be more useful.

### PR DESCRIPTION
**Pull request by shynline**
#111
Pitch
Speed

### CODE REVIEW

**Comment by zyrouge** [comment]
LGTM!

**Comment by RustoMCSpit** [comment]
may i ask why pitch has 2x in the middle but speed has 1x

**Comment by zyrouge** [comment]
> may i ask why pitch has 2x in the middle but speed has 1x

I'll patch that. No worries.

**Comment by shynline** [comment]
The middle one shows the current value. @RustoMCSpit

**Comment by RustoMCSpit** [comment]
can we have a lock toggle where speed and pitched are locked to the same value?

**Comment by RustoMCSpit** [comment]
> can we have a lock toggle where speed and pitched are locked to the same value?

as in, moving one moves the other? maybe also have them displayed on the same window

**Comment by CubeOfCheese** [comment]
What menu is this in? Haven't been able to find it in the app

**Comment by zyrouge** [comment]
> What menu is this in? Haven't been able to find it in the app

Click the three dots on bottom right of the Now Playing view.

**Comment by CubeOfCheese** [comment]
Oh interesting. Those three dots are not visible when I have my language set to spanish. I tried switching language to English and see the controls now

**Pull request merged**
