### PR TITLE
add reverb stuff

### PR DESCRIPTION
**Pull request by RustoMCSpit**
no idea if i did this right, ive never worked with kotlin or android studio or even git so im sending in an early fork.

### CODE REVIEW

**Comment by RustoMCSpit** [comment]
https://github.com/zyrouge/symphony/issues/288

**Comment by RustoMCSpit** [comment]
if i did something dumb tell me lol

**Comment by zyrouge** [comment]
LGTM!

**Comment by RustoMCSpit** [comment]
> LGTM!

i did not build the app myself and do not know if it works, just to be clear

**Comment by RustoMCSpit** [comment]
also if youre adding this merge to the milestone you should add this too #288

**Comment by RustoMCSpit** [comment]
also i saw there were different types of reverb which if you want you could add a selector in the settings

**Comment by zyrouge** [comment]
> > LGTM!
> 
> i did not build the app myself and do not know if it works, just to be clear

Yup, it does not work. There is no `.setReveb()` in `MediaPlayer`.

**Comment by RustoMCSpit** [comment]
> > > LGTM!
> > 
> > 
> > i did not build the app myself and do not know if it works, just to be clear
> 
> Yup, it does not work. There is no `.setReveb()` in `MediaPlayer`.

sorry! i think you mean .setReverb() ?

**Comment by zyrouge** [comment]
> > > > LGTM!
> > > 
> > > 
> > > i did not build the app myself and do not know if it works, just to be clear
> > 
> > 
> > Yup, it does not work. There is no `.setReveb()` in `MediaPlayer`.
> 
> sorry! i think you mean .setReverb() ? i dont think you need to revert the merge as most of the code is still good

I did check if there were possible fixes but there are none. There was too many changing to keep track of, it was easier to revert.

**Comment by RustoMCSpit** [comment]
> > 
> 
> I did check if there were possible fixes but there are none. There was too many changing to keep track of, it was easier to revert.

so just add it to the milestones then?

**Comment by zyrouge** [comment]
> > > 
> > 
> > 
> > I did check if there were possible fixes but there are none. There was too many changing to keep track of, it was easier to revert.
> 
> so just add it to the milestones then?

There was already many things in upcoming milestones. I can't add it unless I have a possible implementation.

**Comment by RustoMCSpit** [comment]
backlog?

**Comment by zyrouge** [comment]
> > I can't add it unless I have a possible implementation.
> 
> https://developer.android.com/reference/android/media/audiofx/PresetReverb

I already did see that. It does not allow much customization.

**Pull request merged**
