### PR TITLE
Update Russian, Belarusian, Ukrainian and German translations

### PR DESCRIPTION
**Pull request by Atrafon**

### CODE REVIEW

**Comment by zyrouge** [comment]
Request review when it's ready to be merge.

**Comment by zyrouge** [comment]
@Atrafon Is this ready yet?

**Comment by Atrafon** [comment]
Hi. I find it easier to make a new merge-ready PR.  May I do this?

**Comment by zyrouge** [comment]
> Hi. I find it easier to make a new merge-ready PR. May I do this?

Sure.

**Pull request closed without merging**
